/**
 * Wedding
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface APIGuest { 
    firstName: string;
    lastName: string;
    mehndiAccepted: number;
    civilAccepted: number;
    receptionAccepted: number;
    rsvpType?: number;
    email: string;
    whiteWine?: boolean;
    redWine?: boolean;
    roseWine?: boolean;
    beer?: boolean;
    vodka?: boolean;
    gin?: boolean;
    whiskey?: boolean;
    rum?: boolean;
    disaronno?: boolean;
    nonAlcoholicOption?: boolean;
    vegan?: boolean;
    jain?: boolean;
}
