/**
 * Cen API
 * CenAPI
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EncodedProgress } from './encodedProgress';
import { Mark } from './mark';
import { Source } from './source';


export interface Clip {
    uuid: string;
    startMark?: Mark;
    endMark?: Mark;
    fileName?: string;
    lockedIn?: boolean;
    encodedProgress?: EncodedProgress;
    published?: boolean;
    source?: Source;
}
