/**
 * Cen API
 * CenAPI
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { EncodedProgress } from '../model/encodedProgress';
import { Source } from '../model/source';
import { SourceInfo } from '../model/sourceInfo';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class PrivateService {

    protected basePath = 'https://api.kilwaz.me';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Retrieves source encoding information
     * 
     * @param uuid Pass a uuid to return an encoded progress object
     * @param filter Comma Separated list of specific values to return
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getEncodedProgress(uuid: string, filter?: string, observe?: 'body', reportProgress?: boolean): Observable<Array<EncodedProgress>>;
    public getEncodedProgress(uuid: string, filter?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<EncodedProgress>>>;
    public getEncodedProgress(uuid: string, filter?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<EncodedProgress>>>;
    public getEncodedProgress(uuid: string, filter?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (uuid === null || uuid === undefined) {
            throw new Error('Required parameter uuid was null or undefined when calling getEncodedProgress.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (uuid !== undefined) {
            queryParameters = queryParameters.set('uuid', <any>uuid);
        }
        if (filter !== undefined) {
            queryParameters = queryParameters.set('filter', <any>filter);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<EncodedProgress>>(`${this.basePath}/encodedProgress`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieves source information
     * 
     * @param uuid Pass an optional uuid to return just that one
     * @param filter Comma Separated list of specific values to return
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSource(uuid?: string, filter?: string, observe?: 'body', reportProgress?: boolean): Observable<Array<Source>>;
    public getSource(uuid?: string, filter?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Source>>>;
    public getSource(uuid?: string, filter?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Source>>>;
    public getSource(uuid?: string, filter?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (uuid !== undefined) {
            queryParameters = queryParameters.set('uuid', <any>uuid);
        }
        if (filter !== undefined) {
            queryParameters = queryParameters.set('filter', <any>filter);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<Source>>(`${this.basePath}/source`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieves detailed information about a source
     * 
     * @param uuid Pass a uuid to return an encoded progress object
     * @param filter Comma Separated list of specific values to return
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSourceInfo(uuid: string, filter?: string, observe?: 'body', reportProgress?: boolean): Observable<Array<SourceInfo>>;
    public getSourceInfo(uuid: string, filter?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<SourceInfo>>>;
    public getSourceInfo(uuid: string, filter?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<SourceInfo>>>;
    public getSourceInfo(uuid: string, filter?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (uuid === null || uuid === undefined) {
            throw new Error('Required parameter uuid was null or undefined when calling getSourceInfo.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (uuid !== undefined) {
            queryParameters = queryParameters.set('uuid', <any>uuid);
        }
        if (filter !== undefined) {
            queryParameters = queryParameters.set('filter', <any>filter);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<SourceInfo>>(`${this.basePath}/sourceInfo`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
